---

- hosts: webservers
  become: true
  tasks:

  - name: Install Apache Package
    package: 
      name: 
        - "{{ apache_package }}"
        - htop
      state: latest
      update_cache: yes
