---

- hosts: webservers
  become: true
  tasks:

  - name: Update the Repository Index
    apt:
      update_cache: yes

  - name: Remove Apache2 Package
    apt: 
      name: apache2
      state: absent

